spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  cookie:
    secure: false   # 로컬 http 개발용

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
